# Copyright (c) 2026 Intel Corporation
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
from glob import glob

from defusedxml import ElementTree as ET


def parse_xml_report(xml_file) -> list:
    """
    Parse the XML report generated by pytest.

    :param xml_file: Path to the XML report file
    :return: List of table lines
    """
    try:
        tree = ET.parse(xml_file)
    except FileNotFoundError:
        return []

    root = tree.getroot()

    table_lines = []

    # Iterate over test cases
    for testcase in root.findall(".//testcase"):
        test_name = testcase.get("name")
        time_duration = float(testcase.get("time", "0"))
        message = ""
        if testcase.find("failure") is not None:
            status = "Failed"
            message = testcase.find("failure").get("message", "")
        elif testcase.find("error") is not None:
            status = "Error"
        elif testcase.find("skipped") is not None:
            if "xfail" in testcase.find("skipped").get("type", ""):
                status = "Xfail"
                message = testcase.find("skipped").get("message", "")
            else:
                status = "Skipped"
                message = testcase.find("skipped").get("message", "")
        else:
            status = "Ok"

        # Append each row to the table
        if message:
            message = message.splitlines()[0][:60]
        table_lines.append(f"| {test_name} | {status} | {time_duration:.0f} | {message} |")

    return table_lines


if __name__ == "__main__":
    """
    This script generates a summary table in Markdown format from XML reports generated by pytest.
    Supports multiple XML files and glob patterns.

    Usage in GitHub workflow:
        - name: Test Summary
        if: ${{ !cancelled() }}
        run: |
            python .github/scripts/pytest_md_summary.py test-results/*/pytest-results.xml >> $GITHUB_STEP_SUMMARY
    """
    try:
        xml_files = []
        for pattern in sys.argv[1:]:
            xml_files.extend(glob(pattern))

        if not xml_files:
            sys.exit(1)

        all_rows = []
        for xml_file in sorted(xml_files):
            all_rows.extend(parse_xml_report(xml_file))

        if all_rows:
            print("| Test Name | Status | Time | Message |")
            print("|:----------|:------:|-----:|:--------|")
            print("\n".join(all_rows))
    except Exception as e:
        print(f"Error: {e}")
