# Default state for all rules
default: true

MD013: false  # Line length
MD033: false  # Inline HTML
MD034: false  # Bare URL used
MD036: false  # Emphasis used instead of a heading
MD037: false  # Spaces inside emphasis markers
MD041: false  # First line
