[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nncf"
description = "Neural Networks Compression Framework"
readme = "docs/PyPiPublishing.md"
license = "Apache-2.0"
authors = [{ name = "Intel" }, { email = "maksim.proshin@intel.com" }]
requires-python = ">=3.10"
dynamic = ["version"]
keywords = [
    "bert",
    "classification",
    "compression",
    "hawq",
    "mixed-precision-training",
    "mmdetection",
    "nas",
    "nlp",
    "object-detection",
    "pruning",
    "quantization",
    "quantization-aware-training",
    "semantic-segmentation",
    "sparsity",
    "transformers",
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "networkx>=2.6, <=3.6.1",
    "ninja>=1.10.0.post2, <1.14",
    "numpy>=1.24.0, <2.5.0",
    "openvino-telemetry>=2023.2.0",
    "packaging>=20.0",
    "psutil",
    "pydot>=1.4.1, <=3.0.4",
    "rich>=13.5.2",
    "safetensors>=0.4.1",
    "scikit-learn>=0.24.0",
    "scipy>=1.3.2",
    "tabulate>=0.9.0",
]

[project.optional-dependencies]
plots = [
    "kaleido>=0.2.1",
    "matplotlib>=3.3.4",
    "pandas>=1.1.5,<2.4",
    "pillow>=9.0.0",
    "plotly-express>=0.4.1",
]

[project.urls]
Homepage = "https://github.com/openvinotoolkit/nncf"

[tool.uv]
extra-index-url = ["https://storage.openvinotoolkit.org/simple/wheels/nightly"]
prerelease = "allow"
index-strategy = "unsafe-best-match"

[tool.setuptools.dynamic]
version = { attr = "custom_version.version" }

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.md_dead_link_check]
exclude_files = ["ReleaseNotes.md"]

[tool.mypy]
follow_imports = "silent"
strict = true
files = ["src"]
exclude = [
    "src/nncf/experimental/*",
    "src/nncf/onnx/graph/metatypes/onnx_metatypes.py",
    "src/nncf/onnx/graph/model_transformer.py",
    "src/nncf/onnx/graph/model_utils.py",
    "src/nncf/onnx/graph/nncf_graph_builder.py",
    "src/nncf/onnx/graph/node_utils.py",
    "src/nncf/onnx/graph/onnx_helper.py",
    "src/nncf/onnx/graph/passes.py",
    "src/nncf/onnx/graph/transformations/command_creation.py",
    "src/nncf/onnx/graph/transformations/commands.py",
    "src/nncf/onnx/quantization/backend_parameters.py",
    "src/nncf/onnx/quantization/quantize_model.py",
    "src/nncf/onnx/quantization/quantizer_parameters.py",
    "src/nncf/onnx/statistics/aggregator.py",
    "src/nncf/openvino/graph/layout.py",
    "src/nncf/openvino/graph/metatypes/openvino_metatypes.py",
    "src/nncf/openvino/graph/model_transformer.py",
    "src/nncf/openvino/graph/nncf_graph_builder.py",
    "src/nncf/openvino/graph/node_utils.py",
    "src/nncf/openvino/graph/transformations/command_creation.py",
    "src/nncf/openvino/optimized_functions/functions.py",
    "src/nncf/openvino/optimized_functions/models.py",
    "src/nncf/openvino/quantization/backend_parameters.py",
    "src/nncf/openvino/quantization/default_quantization.py",
    "src/nncf/openvino/quantization/quantize_ifmodel.py",
    "src/nncf/openvino/quantization/quantize_model.py",
    "src/nncf/openvino/statistics/aggregator.py",
    "src/nncf/openvino/statistics/builders.py",
    "src/nncf/openvino/statistics/collectors.py",
    "src/nncf/quantization/algorithms/accuracy_control/algorithm.py",
    "src/nncf/quantization/algorithms/accuracy_control/backend.py",
    "src/nncf/quantization/algorithms/accuracy_control/evaluator.py",
    "src/nncf/quantization/algorithms/accuracy_control/onnx_backend.py",
    "src/nncf/quantization/algorithms/accuracy_control/openvino_backend.py",
    "src/nncf/quantization/algorithms/accuracy_control/rank_functions.py",
    "src/nncf/quantization/algorithms/accuracy_control/ranker.py",
    "src/nncf/quantization/algorithms/accuracy_control/subset_selection.py",
    "src/nncf/quantization/algorithms/bias_correction/algorithm.py",
    "src/nncf/quantization/algorithms/bias_correction/onnx_backend.py",
    "src/nncf/quantization/algorithms/bias_correction/openvino_backend.py",
    "src/nncf/quantization/algorithms/bias_correction/torch_fx_backend.py",
    "src/nncf/quantization/algorithms/channel_alignment/algorithm.py",
    "src/nncf/quantization/algorithms/channel_alignment/backend.py",
    "src/nncf/quantization/algorithms/channel_alignment/openvino_backend.py",
    "src/nncf/quantization/algorithms/fast_bias_correction/algorithm.py",
    "src/nncf/quantization/algorithms/fast_bias_correction/backend.py",
    "src/nncf/quantization/algorithms/fast_bias_correction/onnx_backend.py",
    "src/nncf/quantization/algorithms/fast_bias_correction/openvino_backend.py",
    "src/nncf/quantization/algorithms/fast_bias_correction/torch_backend.py",
    "src/nncf/quantization/algorithms/fast_bias_correction/torch_fx_backend.py",
    "src/nncf/quantization/algorithms/hyperparameter_tuner/algorithm.py",
    "src/nncf/quantization/algorithms/hyperparameter_tuner/param_grid.py",
    "src/nncf/quantization/algorithms/layerwise/backend.py",
    "src/nncf/quantization/algorithms/layerwise/engine.py",
    "src/nncf/quantization/algorithms/layerwise/iterator.py",
    "src/nncf/quantization/algorithms/layerwise/openvino_backend.py",
    "src/nncf/quantization/algorithms/layerwise/openvino_iterator.py",
    "src/nncf/quantization/algorithms/layerwise/scheduler.py",
    "src/nncf/quantization/algorithms/min_max/algorithm.py",
    "src/nncf/quantization/algorithms/min_max/backend.py",
    "src/nncf/quantization/algorithms/min_max/onnx_backend.py",
    "src/nncf/quantization/algorithms/min_max/openvino_backend.py",
    "src/nncf/quantization/algorithms/min_max/torch_backend.py",
    "src/nncf/quantization/algorithms/min_max/torch_fx_backend.py",
    "src/nncf/quantization/algorithms/pipeline.py",
    "src/nncf/quantization/algorithms/post_training/algorithm.py",
    "src/nncf/quantization/algorithms/post_training/pipeline.py",
    "src/nncf/quantization/algorithms/smooth_quant/algorithm.py",
    "src/nncf/quantization/algorithms/smooth_quant/backend.py",
    "src/nncf/quantization/algorithms/smooth_quant/onnx_backend.py",
    "src/nncf/quantization/algorithms/smooth_quant/openvino_backend.py",
    "src/nncf/quantization/algorithms/smooth_quant/torch_backend.py",
    "src/nncf/quantization/algorithms/smooth_quant/torch_fx_backend.py",
    "src/nncf/quantization/algorithms/weight_compression/activation_stats.py",
    "src/nncf/quantization/algorithms/weight_compression/algorithm.py",
    "src/nncf/quantization/algorithms/weight_compression/awq.py",
    "src/nncf/quantization/algorithms/weight_compression/awq_patterns.py",
    "src/nncf/quantization/algorithms/weight_compression/backend.py",
    "src/nncf/quantization/algorithms/weight_compression/fp8_conversion.py",
    "src/nncf/quantization/algorithms/weight_compression/gptq.py",
    "src/nncf/quantization/algorithms/weight_compression/lora_correction.py",
    "src/nncf/quantization/algorithms/weight_compression/mixed_precision.py",
    "src/nncf/quantization/algorithms/weight_compression/onnx_backend.py",
    "src/nncf/quantization/algorithms/weight_compression/openvino_backend.py",
    "src/nncf/quantization/algorithms/weight_compression/parameters.py",
    "src/nncf/quantization/algorithms/weight_compression/scale_estimation.py",
    "src/nncf/quantization/algorithms/weight_compression/torch_backend.py",
    "src/nncf/quantization/algorithms/weight_compression/torch_fx_backend.py",
    "src/nncf/quantization/algorithms/weight_compression/weight_lowering.py",
    "src/nncf/torch/__init__.py",
    "src/nncf/torch/graph/operator_metatypes.py",
    "src/nncf/torch/graph/transformations/commands.py",
    "src/nncf/torch/initialization.py",
    "src/nncf/torch/model_graph_manager.py",
    "src/nncf/torch/quantization/layers.py",
    "src/nncf/torch/quantization/quantize_functions.py",
    "src/nncf/torch/quantization/reference.py",
    "src/nncf/torch/quantization/strip.py",
    "src/nncf/torch/return_types.py",
]
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = "nncf.tensor.functions.*"
disable_error_code = ["empty-body", "no-any-return"]

[[tool.mypy.overrides]]
module = ["transformers.*"]
ignore_missing_imports = true

[tool.ruff]
line-length = 120
exclude = ["src/nncf/torch/function_hook/handle_inner_functions.py"]

[tool.ruff.lint]
preview = true
ignore = [
    "E203",    # whitespace-before-punctuation
    "E251",    # unexpected-spaces-around-keyword-parameter-equals
    "E731",    # lambda-assignment
    "SIM108",  # if-else-block-instead-of-if-exp
    "SIM110",  # reimplemented-builtin
    "SIM117",  # multiple-with-statements
    "SIM103",  # needless-bool
    "NPY002",  # numpy-legacy-random
    "UP035",   # deprecated-import
    "D100",    # undocumented-public-module
    "D101",    # undocumented-public-class
    "D102",    # undocumented-public-method
    "D103",    # undocumented-public-function
    "D104",    # undocumented-public-package
    "D105",    # undocumented-magic-method
    "D106",    # undocumented-public-nested-class
    "D107",    # undocumented-public-init
    "D200",    # unnecessary-multiline-docstring
    "D203",    # incorrect-blank-line-before-class
    "D205",    # missing-blank-line-after-summary
    "D212",    # multi-line-summary-first-line
    "D400",    # missing-trailing-period
    "D401",    # non-imperative-mood
    "D402",    # signature-in-docstring
    "D404",    # docstring-starts-with-this
    "D413",    # missing-blank-line-after-last-section
    "D415",    # missing-terminal-punctuation
    "D417",    # undocumented-param
    "PERF203", # try-except-in-loop
    "PERF401", # manual-list-comprehension
    "PERF403", # manual-dict-comprehension
    "B905",    # zip-without-explicit-strict
    "RET502",  # implicit-return-value
    "RET503",  # implicit-return
    "RET504",  # unnecessary-assign
    "TD003",   # todo-missing-issue
]
select = [
    "CPY001", # copyright check
    "D",      # pydocstyle
    "E",      # pycodestyle rules
    "EM",     # flake8-errmsg
    "F",      # pyflakes rules
    "I",      # isort
    "INP",    # flake8-no-pep420
    "ISC",    # flake8-implicit-str-concat
    "NPY",    # numpy rules
    "UP",     # pyupgrade
    "PERF",   # perflint
    "B",      # flake8-bugbear
    "RET",    # flake8-return
    "PTH",    # flake8-use-pathlib
    "TD",     # flake8-todos
]
extend-select = [
    "SIM", # https://pypi.org/project/flake8-simplify
]

[tool.ruff.lint.per-file-ignores]
"src/nncf/torch/__init__.py" = ["F401", "E402"]
"tests/**/*.py" = ["F403"]
"tests/**/__init__.py" = ["F401"]
"examples/**/*.py" = ["F403"]
"!src/nncf/**.py" = ["INP", "D", "B", "PTH"]
"*.ipynb" = ["CPY001"]

[tool.ruff.lint.flake8-copyright]
notice-rgx = """\
# Copyright \\(c\\) (202[6,7]) Intel Corporation
# Licensed under the Apache License, Version 2.0 \\(the "License"\\);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""

[tool.ruff.lint.isort]
force-single-line = true
known-third-party = ["datasets"]
single-line-exclusions = ["typing"]

[tool.pytest.ini_options]
pythonpath = "."

[tool.bandit]
exclude_dirs = ["tools", "tests", "**/venv*", "build"]
skips = [
    "B101", # assert_used
    "B404", # import_subprocess
    "B614", # pytorch_load
    "B615", # huggingface_unsafe_download
]
