name: 'Add job link to PR description'
inputs:
  pull_request_number:
    description: 'Pull Request number'
    required: true
  link_name:
    description: 'Name of link, should contain only alphanumeric characters, dashes, and underscores'
    required: true
runs:
  using: "composite"
  steps:
    - name: Update PR description with preview link
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const prNumber = parseInt(${{ inputs.pull_request_number }});
          const newLink = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
          const newLine = `[${{ inputs.link_name }}](${newLink})`;

          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          });

          let body = pr.body || '';
          const regex = /\[${{ inputs.link_name }}\]\([^)]+\)/;

          if (regex.test(body)) {
            body = body.replace(regex, newLine);
          } else {
            body = body.trim() + `\n\n${newLine}`;
          }

          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            body
          });
