name: call-precommit
permissions: read-all

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        type: string
        required: true
      gpu_enabled:
        description: 'Enable gpu tests'
        type: boolean
        default: false
      override_requirements:
        description: 'Override requirements'
        default: ''
        type: string
        required: false

jobs:

  Smart_CI:
    runs-on: ubuntu-latest
    outputs:
      changed_components: "${{ steps.smart_ci.outputs.changed_components }}"
    steps:
      - uses: openvinotoolkit/openvino/.github/actions/smart-ci@b92810a6d7b48db3697cfb3496e84a9642bd5482
        id: smart_ci
        with:
          repository: ${{ github.repository }}
          pr: ${{ github.event.number }}
          commit_sha: ${{ github.sha }}
          ref_name: ${{ github.ref_name }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          labeler_config: '.github/action_configs/labeler.yml'
          components_config: '.github/action_configs/components.yml'
          labeler_check_name: 'set-label'

  docker:
    needs: Smart_CI
    name: Docker
    timeout-minutes: 15
    runs-on: aks-linux-4-cores-16gb-docker-build
    if: ${{ inputs.gpu_enabled == true }}
    container:
      image: openvinogithubactions.azurecr.io/docker_build:0.2
      volumes:
        - /mount:/mount
    outputs:
      images: "${{ steps.handle_docker.outputs.images }}"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: openvinotoolkit/openvino/.github/actions/handle_docker@1f6bb04df50d71dd7e392537eee6b834312f269a
        id: handle_docker
        with:
          images: |
            nncf/pytorch_cuda
          registry: 'openvinogithubactions.azurecr.io'
          dockerfiles_root_dir: '.github/dockerfiles'
          changed_components: ${{ needs.Smart_CI.outputs.changed_components }}

  pytorch-cuda:
    timeout-minutes: 40
    needs: docker
    runs-on:
      group: Nvidia-GPU
      labels: [Linux, NNCF]
    if: ${{ inputs.gpu_enabled == true }}
    container:
      image: ${{ fromJSON(needs.docker.outputs.images).nncf.pytorch_cuda }}
      options: --gpus all --ipc=host
      volumes:
        - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
    defaults:
      run:
        shell: bash
    steps:
      - name: Update CA certificates
        run: update-ca-certificates

      - name: Runner info
        continue-on-error: true
        run: |
          nvidia-smi
          cat /proc/cpuinfo

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true

      # - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      #   with:
      #     python-version: ${{ inputs.python_version }}

      # - name: Create virtual environment
      #   run: |
      #     python3 -m venv .venv
      #     echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Override constraints
        if: ${{ inputs.override_requirements != '' }}
        run: python .github/scripts/override_constraints.py "${{ inputs.override_requirements }}"
        shell: bash

      - name: Install NNCF and test requirements
        run: pip install . -r tests/torch/requirements.txt

      - name: Print installed modules
        run: pip list

      - name: Check CUDA
        run: |
          python -c "import torch; print(torch.cuda.is_available())"

      - name: Run PyTorch precommit test scope
        run: |
          pytest -ra --durations=30 tests/torch -m cuda
