name: call-precommit-windows
permissions: read-all

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Python version'
        type: string
        required: true
      override_requirements:
        description: 'Override requirements'
        default: ''
        type: string
        required: false

defaults:
  run:
    shell: bash

jobs:
  common:
    timeout-minutes: 40
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python_version }}
      - name: Override constraints
        if: ${{ inputs.override_requirements != '' }}
        run: python .github/scripts/override_constraints.py "${{ inputs.override_requirements }}"
      - name: Install NNCF and test requirements
        run: pip install . -r tests/common/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run common precommit test scope
        run: make test-common
        env:
          NUM_WORKERS: 2

  onnx:
    timeout-minutes: 40
    runs-on: windows-2025-8-core
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python_version }}
      - name: Override constraints
        if: ${{ inputs.override_requirements != '' }}
        run: python .github/scripts/override_constraints.py "${{ inputs.override_requirements }}"
      - name: Install NNCF and test requirements
        run: pip install . -r tests/onnx/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run ONNX precommit test scope
        run: make test-onnx
        env:
          NUM_WORKERS: 4

  openvino:
    timeout-minutes: 40
    runs-on: windows-2025-8-core
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python_version }}
      - name: Override constraints
        if: ${{ inputs.override_requirements != '' }}
        run: python .github/scripts/override_constraints.py "${{ inputs.override_requirements }}"
      - name: Install NNCF and test requirements
        run: pip install . -r tests/openvino/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run OV precommit test scope
        run: make test-openvino
        env:
          NUM_WORKERS: 4

  pytorch-cpu:
    timeout-minutes: 40
    runs-on: windows-2025-8-core
    env:
      NNCF_EXTENSION_LOAD_TIMEOUT: 180
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python_version }}
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
      - name: Override constraints
        if: ${{ inputs.override_requirements != '' }}
        run: python .github/scripts/override_constraints.py "${{ inputs.override_requirements }}"
      - name: Install NNCF and test requirements
        run: |
          pip install . -r tests/torch/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run torch precommit test scope
        run: |
          set +e

          sys_lib="$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")"
          prefix_lib="$(python -c "import sys; print(sys.prefix + '/libs')")"
          include_dir="$(python -c "import sysconfig; print(sysconfig.get_path('include'))")"

          export LIB="${LIB};${sys_lib};${prefix_lib}"
          export INCLUDE="${INCLUDE};${include_dir}"

          pytest -ra tests/torch -m "not cuda"
