name: Check Documentation
permissions: read-all

on:
  pull_request:

jobs:
  check_docs:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
      - name: Install test requirements
        run: pip install -r tests/docs/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run pytest
        run: pytest -ra tests/docs
