name: Test examples
permissions: read-all

on:
  pull_request:

defaults:
  run:
    shell: bash

env:
  TQDM_DISABLE: 1
  RESULT_XML: "pytest-results.xml"
  PYTHON_VERSION: "3.12"

jobs:
  examples-cpu:
    name: Test examples CPU [${{ matrix.group }}/6]
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 80
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: cpuinfo
        run: cat /proc/cpuinfo
      - name: Install test requirements
        run: |
          pip install -r tests/cross_fw/examples/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run examples test scope
        run: |
          set +e
          python -m pytest -s -ra tests/cross_fw/examples
