name: Test install
permissions: read-all

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'The pull request number'
        default: ''
  pull_request:

jobs:
  install-cpu:
    name: Test install [${{ matrix.backend }} - ${{ matrix.runner }}]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        backend:  ["torch", "onnx", "openvino"]
        runner: ["windows-latest", "ubuntu-latest"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
            lfs: true
            fetch-depth: 0  # Fetch full history to allow checking out any branch or PR
      - name: Fetch and Checkout the Pull Request Branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pull_request_number != '' }}
        run: |
          git fetch origin pull/${{ github.event.inputs.pull_request_number }}/head:pr-${{ github.event.inputs.pull_request_number }}
          git checkout pr-${{ github.event.inputs.pull_request_number }}
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
      - name: Install test requirements
        run: |
          pip install -r tests/cross_fw/examples/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run install test scope
        run: pytest tests/cross_fw/install -rA -s --host-configuration cpu --backend ${{ matrix.backend }}

  build_cuda_docker:
    uses: ./.github/workflows/call_build_docker.yml
    with:
      images: |
        nncf/pytorch_cuda

  install-torch-gpu:
    name: Test install [torch - ubuntu-gpu]
    needs: build_cuda_docker
    defaults:
      run:
        shell: bash
    runs-on:
      group: Nvidia-GPU
      labels: [Linux, NNCF]
    timeout-minutes: 20
    container:
      image: ${{ fromJSON(needs.build_cuda_docker.outputs.images).nncf.pytorch_cuda }}
      options: --gpus all --ipc=host
      volumes:
        - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
        - /opt/home/actions_runner/actions-runner/pip-cache:/opt/pip-cache
      env:
        # PIP_CACHE_DIR: /opt/pip-cache
        DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update CA certificates
        run: update-ca-certificates

      - name: Runner info
        continue-on-error: true
        run: |
          nvidia-smi
          cat /proc/cpuinfo

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true
      - name: Fetch and Checkout the Pull Request Branch
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pull_request_number != '' }}
        run: |
          git fetch origin pull/${{ github.event.inputs.pull_request_number }}/head:pr-${{ github.event.inputs.pull_request_number }}
          git checkout pr-${{ github.event.inputs.pull_request_number }}

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"

      - name: Register toolcache libpython with the dynamic linker
        run: |
          echo "$pythonLocation/lib" > /etc/ld.so.conf.d/zz-python-toolcache.conf
          ldconfig

      - name: Create virtual environment
        run: |
          python3 -m venv .venv
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - name: Install test requirements
        run: |
          pip install -r tests/cross_fw/examples/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run install test scope
        run: |
          pytest tests/cross_fw/install -rA -s --host-configuration gpu --backend torch
