name: "Pull Request Labeler"
permissions: read-all

on: [pull_request_target]

jobs:
  set-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '.github/action_configs/labeler.yml'
          sync-labels: true
