name: "Pull Request Labeler"
permissions: read-all

on: [pull_request_target]

jobs:
  set-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/labeler@f1a63e87db0c6baf19c5713083f8d00d789ca184 # v6.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '.github/action_configs/labeler.yml'
          sync-labels: true
