name: MacOS
run-name: "MacOS${{ inputs.pr_num != '' && format(' PR#{0}', inputs.pr_num) || '' }}"
permissions: read-all

on:
  workflow_call:
    inputs:
      pr_num:
        description: 'The pull request number'
        type: string
        default: ''
  workflow_dispatch:
    inputs:
      pr_num:
        description: 'The pull request number'
        type: string
        default: ''

env:
  PYTHON_VERSION: "3.10"

jobs:
  precommit-common:
    runs-on: macos-14
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.pr_num != '' && format('refs/pull/{0}/head', inputs.pr_num) || github.ref }}
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install . -r tests/common/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run pre-commit
        run: pytest -n 2 -ra tests/common

  precommit-openvino:
    runs-on: macos-14
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.pr_num != '' && format('refs/pull/{0}/head', inputs.pr_num) || github.ref }}
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install . -r tests/openvino/requirements.txt
      - name: Print installed modules
        run: pip list
      - name: Run pre-commit
        run: pytest -ra tests/openvino
        env:
          ONEDNN_MAX_CPU_ISA: AVX2
