name: mypy
permissions: read-all

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/workflows/mypy.yml'
      - 'pyproject.toml'
      - '**.py'
      - '**.pyi'

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
      - name: Install NNCF
        run: |
          pip install . torch onnx onnxruntime openvino -c constraints.txt
      - name: Install mypy
        run: pip install mypy==1.8.0
      - name: Run mypy
        run: mypy --install-types --non-interactive
